version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: beyazkemal/jakarta-ee-learning
    docker:
      - image: circleci/buildpack-deps:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

jobs:
  test:
    docker:
      - image: adoptopenjdk/maven-openjdk11
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Maven Test
          command: mvn test

  build:
    docker:
      - image: adoptopenjdk/maven-openjdk11
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Build WAR File
          command: mvn -Dmaven.test.skip=true package
      - persist_to_workspace:
         root: ./
         paths:
           - target/jakarta-ee-learning.war

  build-docker-image:
    executor: docker-publisher
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker Image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  push-docker-hub:
    executor: docker-publisher
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - setup_remote_docker
      - run: |
          set +o pipefail
          docker load -i ./image.tar | true
      - run: |
          docker login --username $DOCKERHUB_USER
          docker push beyazkemal/jakarta-ee-learning:latest

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-docker-image:
          requires:
            - test
      - push-docker-hub:
          requires:
            - build-docker-image