version: 2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: ls -ann
      - run: echo 'Hello Test!'
      - run: sudo ./mvnw test

  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: ls -ann
      - run: echo 'Hello!'
      - run: ./mvnw -Dmaven.test.skip=true package


workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
