version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: beyazkemal/jakarta-ee-learning
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  test:
    docker:
      - image: adoptopenjdk/maven-openjdk11
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: ls -ann
      - run: echo 'Hello Test!'
      - run: mvn test

  build:
    docker:
      - image: adoptopenjdk/maven-openjdk11
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: mvn -Dmaven.test.skip=true package
      - persist_to_workspace:
         root: ./
         paths:
           - target/

  build-docker-image:
    executor: docker-publisher
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: ls -ann
      - setup_remote_docker
      - run: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  push-docker-hub:
    executor: docker-publisher
    steps:
      - checkout
      - run: ls -ann

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-docker-image:
          requires:
            - test
      - push-docker-hub:
          requires:
            - build-docker-image